CREATE TABLE COMPANY
(
    COMPANY_ID   INT(20)      NOT NULL AUTO_INCREMENT,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    ADDRESS      VARCHAR(255),
    PRIMARY KEY (COMPANY_ID)
);

INSERT INTO COMPANY
VALUES (NULL, 'OOCL', 'Rd.SSP'),
       (NULL, 'CMA AGM', 'France');